name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
jobs:
  unit_tests:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install guile-3.0-dev
      - name: Install Rust Test Tools
        run: |
          # Installs nexte.st for nicer test output.
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Test
        run: cargo nextest run
        env:
          # Guile is single threaded so tests cannot run concurrently.
          RUST_TEST_THREADS: 1
